### ISSUE TITLE
训练出现问题，求解答

### ISSUE THREAD

**Issue by lyk595** [hhaAndroid/mmdetection-mini#45]
Traceback (most recent call last):
  File "D:/MachineLearning/unet/mmdetection-mini-master/tools/train.py", line 11, in <module>
    import mmdet.cv_core
  File "D:\MachineLearning\unet\mmdetection-mini-master\tools\..\mmdet\cv_core\__init__.py", line 15, in <module>
    from .ops import *
  File "D:\MachineLearning\unet\mmdetection-mini-master\tools\..\mmdet\cv_core\ops\__init__.py", line 3, in <module>
    from .cc_attention import CrissCrossAttention
  File "D:\MachineLearning\unet\mmdetection-mini-master\tools\..\mmdet\cv_core\ops\cc_attention.py", line 9, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\MachineLearning\unet\mmdetection-mini-master\tools\..\mmdet\cv_core\utils\ext_loader.py", line 10, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: ca_forward miss in module _ext

Process finished with exit code 1

**Comment by colorfully-ybf** [comment]
+1

**Comment by shncg** [comment]
有解决的吗

**Comment by liguopeng0923** [comment]
同问

**Comment by Nancy-197** [comment]
> 同问

mmcv-full版本的问题

**Comment by wwcc1107** [comment]
I also encountered this problem recently. Have you solved it

**Comment by Nancy-197** [comment]
> I also encountered this problem recently. Have you solved it

Reduce the version of mmcv, it is recommended to use version 1.3.5.

**Comment by wwcc1107** [comment]
> 

thank you very much,when i lower the version,i found this problem:
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.2.

**Comment by PiseyYou** [comment]
> Traceback (most recent call last): File "D:/MachineLearning/unet/mmdetection-mini-master/tools/train.py", line 11, in import mmdet.cv_core File "D:\MachineLearning\unet\mmdetection-mini-master\tools..\mmdet\cv_core__init__.py", line 15, in from .ops import * File "D:\MachineLearning\unet\mmdetection-mini-master\tools..\mmdet\cv_core\ops__init__.py", line 3, in from .cc_attention import CrissCrossAttention File "D:\MachineLearning\unet\mmdetection-mini-master\tools..\mmdet\cv_core\ops\cc_attention.py", line 9, in ext_module = ext_loader.load_ext( File "D:\MachineLearning\unet\mmdetection-mini-master\tools..\mmdet\cv_core\utils\ext_loader.py", line 10, in load_ext assert hasattr(ext, fun), f'{fun} miss in module {name}' AssertionError: ca_forward miss in module _ext
> 
> Process finished with exit code 1

the same problem, try different way from version part, still not working...
