### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int64'

### ISSUE THREAD

**Issue by wwcc1107** [hhaAndroid/mmdetection-mini#49]

**Comment by wwcc1107** [comment]
python /home/mmdetection/tools/featuremap_analyze.py /home/mmdetection/configs/yolo/yolov3_mobilenetv2_320_300e_coco.py /home/mmdetection/mmdetection/checkpoints/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth --img_dir /home/mmdetection/demo/demo --output_dir /home/mmdetection/Dataset/dir

when i want to use it in mmdetection ,there is an error.

Error:
Traceback (most recent call last):
  File "/home/wangchang2/mmdetection/mmdetection/tools/featuremap_analyze.py", line 5, in <module>
    import cv2
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/cv2/__init__.py", line 11, in <module>
    import numpy
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/numpy/__init__.py", line 138, in <module>
    from ._version import get_versions
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/numpy/_version.py", line 7, in <module>
    import json
  File "/home/wangchang2/mmdetection/mmdetection/tools/json.py", line 5, in <module>
    import mmcv
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/arraymisc/quantization.py", line 5, in <module>
    def quantize(arr, min_val, max_val, levels, dtype=np.int64):
AttributeError: module 'numpy' has no attribute 'int64'

**Comment by wwcc1107** [comment]
just lower numpy to 1.19.0,it works
