### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.utils.contextmanagers'

### ISSUE THREAD

**Issue by xuezhongcailian** [hhaAndroid/mmdetection-mini#9]
作者你好，在运行train例子的时候，出现这个问题，怎么弄呢

**Comment by hhaAndroid** [comment]
这不是我代码吧，我都没有这个contextmanagers类啊

**Comment by ChenCVer** [comment]
海爷回深圳了？



---Original---

**Comment by Miki-lin** [comment]
> 这不是我代码吧，我都没有这个contextmanagers类啊

你好，我用了你的代码，也有这个问题
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (inference_detector,
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/apis/inference.py", line 10, in <module>
    from mmdet.models import build_detector
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/models/dense_heads/__init__.py", line 1, in <module>
    from .rpn_head import RPNHead
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/models/dense_heads/rpn_head.py", line 9, in <module>
    from .rpn_test_mixin import RPNTestMixin
  File "/home/miki/project/object_detection/mmdetection-mini/mmdet/models/dense_heads/rpn_test_mixin.py", line 6, in <module>
    from mmdet.utils.contextmanagers import completed
ModuleNotFoundError: No module named 'mmdet.utils.contextmanagers'

出错的地方在 rpn_test_mixin.py
import sys

from mmdet.det_core import merge_aug_proposals

if sys.version_info >= (3, 7):
    from mmdet.utils.contextmanagers import completed
请问怎么解决这个问题呢，谢谢！

**Comment by Miki-lin** [comment]
我把这段注释掉了可以运行
